---
title: \vspace{2in} 项目管理计划书
subtitle: "DCGAN-tensorflow"
author:
  - Shi, Ruixin^[Equal Contribution, Fudan University, 17302010065 (rxshi17@fudan.edu.cn)]
  - Zhang, Cenyuan^[Equal Contribution, Fudan University, 17302010068 (cenyuanzhang17@fudan.edu.cn)]
  - Zhang, Yihan^[Equal Contribution, Fudan University, 17302010076 (zhangyihan17@fudan.edu.cn)]
  - Wang, Chen^[Equal Contribution, Fudan University, 16307110064 (wangc16@fudan.edu.cn)]
  - Zhang, Hongnian^[Equal Contribution, Fudan University, 17302010061 (17302010061@fudan.edu.cn)]
  - Song, Puqi^[Equal Contribution, Fudan University, 17302010037 (17302010037@fudan.edu.cn)]
  - Huang, Huiru^[Equal Contribution, Fudan University, 17302010080 (17302010080@fudan.edu.cn)]
date: "2020年10月8日"
documentclass: ctexart
output: pdf_document
classoption: "hyperref, a4paper"
---

```{r eval=FALSE, include=FALSE}
tinytex::install_tinytex()
```
\newpage

\LARGE

\begin{center}
\textbf{项目管理计划书}
\end{center}

\large
\begin{center}
\textbf{\emph{DCGAN-tensorflow}}
\end{center}

# 项目摘要 {-}
深卷积生成对抗网络的 Tensorflow 实现


# 关键词 {-}

DCGAN（ Deep Convolutional Generative Adversarial Networks）

\normalsize

\newpage

\tableofcontents

\newpage

# 项目概述
## 用户群

项目成员

在本项目中，项员共有以下几位人员：

- 王宸

- 张逸涵

- 张岑媛

- 石睿欣

- 黄慧茹

- 张宏年

- 宋普琦

## 项目 交付产品
（1）提交文档：项目管理计划，需求规格说明等等
（2）源程序检查：检查系统运行情况

## 项目计划书的演化
 - 第一阶段：2020年9月26日-2020年9月28日
   （1）张宏年、宋普琦：完成项目计划书框架，写入Rmd文档中（编译成的PDF文件>10页）
   （2）张岑湲、黄蕙茹：分析DCGan所依赖的算法理论、预测搭建faces demo所需要的技术框架、所需的人员工作量、时间工作量、时间段安排，将这些分析结果以Rmd的形式进行汇总（编译成的PDF文件>10页）
 
 - 第二阶段：2020年9月29日-2020年10月4日
   石睿欣、张逸涵：将上面（2）的内容填充进入（1）中并补充所缺内容，完善成为完整的项目计划书，得到可以提交的PDF文件（编译成的PDF文件>20页）
 
 - 第三阶段：2020年10月5日-2020年10月8日
   王宸：展示

## 参考资料
URL:'https://github.com/soumith/dcgan.torch'
URLhttps://arxiv.org/abs/1511.06434'
   :'

#  技术过程
## 算法理论
https://github.com/soumith/dcgan.torch
https://arxiv.org/abs/1511.06434


## 开发工具与技术框架
- Python 2.7 or Python 3.3+'

- Tensorflow 0.12.1

- SciPy

- pillow

- tqdm

- （可选）电影（用于可视化）

- （可选）对齐和裁剪图像.zip ： 大型名人脸数据集

#  项目组织

## 过程模型
| 关键时间 | 任务 | 要求  |
| ------ | ------ | ------ |
| ------ | ------ | ------ |
| ------ | ------ | ------ |
| ------ | ------ | ------ |
| ------ | ------ | ------ |
| ------ | ------ | ------ |
| ------ | ------ | ------ |

## 团队分工与合作
| 成员| 角色 | 职责 |
| ------ | ------ | ------ |
| ------ | ------ | ------ |
| ------ | ------ | ------ |
| ------ | ------ | ------ |
| ------ | ------ | ------ |
| ------ | ------ | ------ |
| ------ | ------ | ------ |
## 人员工作量预估
对早期任务量所需人员的预估

## 人员计划
前端：
后端：
。。。。


# 项目进度及关键工期设置
| 工作集 | 子工作 | 完成时间 |负责人|最终交付物|描述|
| ------ | ------ | ------ | ------ | ------ | ------ |
| ------ | ------ | ------ | ------ | ------ | ------ |
| ------ | ------ | ------ | ------ | ------ | ------ |
| ------ | ------ | ------ | ------ | ------ | ------ |
| ------ | ------ | ------ | ------ | ------ | ------ |
| ------ | ------ | ------ | ------ | ------ | ------ |
| ------ | ------ | ------ | ------ | ------ | ------ |


## 项目时间安排
具体的时间安排

## 软件管理过程中预算及资源分配

## 开发过程资源
人员：
- 王宸

- 张逸涵

- 张岑媛

- 石睿欣

- 黄慧茹

- 张宏年

- 宋普琦
开发地点：寝室、机房
支持软件：Rstudio、Python 2.7 or Python 3.3+、、
实验设备：
训练数据集


# 管理过程

## 管理目标及优先级
    基本管理原则：每位组成员既是积极的建言者，又是负责的合作者，同时也是决策的制定者。决策应在充分的讨论基础上由大家共同做出，一旦决策做出就必须被及时有效的执行。禁止再有异议。
    目标 1：按时按量完成项目的基本功能，按时发布产品及文档，这是本团队的最高目标。 
    目标 2：遵循规范化的项目运作标准，文档严谨完整，代码注释充分，便于后续维护，这是第二目标。
## 会议方式
项目需要小组讨论时，协商空余时间，通过线下、钉钉、腾讯等方式展开会议，并进行会议记录


关键节点的时间安排
##  培训计划
学习使用r-markdowm编写文档，了解DCGAN算法原理及实现

##  风险管理
风险类型 | 存在风险 |规避方法 
------|------|------
进度风险 | 由于时间紧张导致最后项目无法完成 | ------ 
技术风险 | ---------------------------------| ------ 
质量风险 | ---------------------------------| ------ 
工具风险 | ---------------------------------| ------ 
人力资源风险 | ---------------------------------| ------ 

## 监督及控制机制
 整理开发日志等等
 
 
## 计划更新策略
  在本节中，应描述项目计划的更新策略，明确说明项目计划更新的发布方法还要说明项目计划进行变更控制和管理的机制以及其载体。
  
在发生如下事件时，修订项目计划和参考文档:
1、到达某里程碑，在每个阶段结束后如思必要的话修订项目计划。
2、项目的范围发生安化
3、当风险成为现实时采取了相应的行动
4、当进度、工作量超出控制的范围并需要采取纠正行动时
## 质量保证活动
内部审核
阶段审核



